RUN_MAVEN = bash mvnw

compile:
	$(RUN_MAVEN) clean compile -DskipTests=true

build:
	$(RUN_MAVEN) clean package -DskipTests=true
.PHONY: build

test:
	$(RUN_MAVEN) clean test

run:
	$(RUN_MAVEN) compile exec:java -Dexec.mainClass=com.template.javaproject.Application

# TODO may add linting/code formatting?